steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/bdi-test-service:$COMMIT_SHA', '.']
    timeout: 500s
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/bdi-test-service:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
    - 'run'
    - 'deploy'
    - 'bdi-test-service-2'
    - '--image'
    - 'gcr.io/$PROJECT_ID/bdi-test-service:$COMMIT_SHA'
    - '--region'
    - 'europe-west1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
images:
  - 'gcr.io/$PROJECT_ID/bdi-test-service:$COMMIT_SHA'