steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/bdi-test-service:$COMMIT_SHA', '.']
    timeout: 500s
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/bdi-test-service:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
    - 'run'
    - 'deploy'
    - 'bdi-test-service'
    - '--image'
    - 'gcr.io/$PROJECT_ID/bdi-test-service:$COMMIT_SHA'
    - '--region'
    - 'europe-west1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'services'
    - 'update-traffic'
    - 'bdi-test-service'
    - '--to-latest'
    - '--region'
    - 'europe-west1'
    - '--platform'
    - 'managed'
    # - name: 'gcr.io/cloud-builders/gcloud'
    # args:
    # - 'run'
    # - 'services'
    # - 'update-traffic'
    # - 'bdi-test-service'
    # - '--to-revisions'
    # - 'LATEST=50,bdi-test-service-00018-pak=50'
    # - '--region'
    # - 'europe-west1'
    # - '--platform'
    # - 'managed'
images:
  - 'gcr.io/$PROJECT_ID/bdi-test-service:$COMMIT_SHA'