name: Cloud Run

on:
  pull_request:
    branches: 
      - main
      - dev_*

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env: 
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      run: docker build . --file Dockerfile --tag gcr.io/$GCP_PROJECT_ID/bdi-test-service:$GITHUB_SHA
  deploy-cloud-run:
    runs-on: ubuntu-latest
    env: 
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
    steps:
      - uses: google-github-actions/deploy-cloudrun@main
        name: Deploy the Cloud Run Service
        with:
          credentials: $${{ secrets.GCP_SA_KEY }}
          image: gcr.io/cloud-run-286409/bdi-test-service
          service: bdi-test-service


