name: Cloud Run
on:
  pull_request:
    branches: 
      - main
      - dev_*
jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
      # - name: extract variable
      #   run: ::set-env name=GCP_PROJECT
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
      - uses: RafikFarhad/push-to-gcr-github-action@v4
        with:
          gcloud_service_key: ${{ secrets.GCP_SA_KEY  }}
          registry: gcr.io
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          image_name: bdi-test-service
          
  deploy-cloud-run:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/deploy-cloudrun@main
        name: Deploy the Cloud Run Service
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/bdi-test-service
          service: bdi-test-service
          region: europe-west1
      - name: list docker images
        run: docker images
    


