name: Cloud Run

on:
  pull_request:
    branches: 
      - main
      - dev_*

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env: 
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      run: docker build . --file Dockerfile --tag gcr.io/$GCP_PROJECT_ID/bdi-test-service:$GITHUB_SHA
