name: Docker Image CI

on:
  pull_request:
    branches: 
      - main
      - dev_*

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env: 
        PROJECT_ID: cloud-run-286409
      run: docker build . --file Dockerfile --tag gcr.io/$PROJECT_ID/bdi-test-service:$COMMIT_SHA
