name: Cloud Run
env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

on:
  pull_request:
    branches: 
      - main
      - dev_*
jobs:
  # build-image:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Build the Docker image
  #     run: docker build . --file Dockerfile --tag gcr.io/$GCP_PROJECT_ID/bdi-test-service:$GITHUB_SHA
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
      - uses: RafikFarhad/push-to-gcr-github-action@v4
        with:
          gcloud_service_key: $${{ secrets.GCP_SA_KEY  }}
          registry: gcr.io
          project_id: cloud-run-286409
          image_name: bdi-test-service
          
  deploy-cloud-run:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/deploy-cloudrun@main
        name: Deploy the Cloud Run Service
        with:
          credentials: $${{ secrets.GCP_SA_KEY }}
          image: gcr.io/cloud-run-286409/bdi-test-service
          service: bdi-test-service
          region: europe-west1
          args: allow-unauthenticated
      - name: list docker images
        run: docker images
    


